# Site settings
title: Joe Castelli's blog
email: your-email@domain.com
description: "The weblog of Joe Castelli – a Cincinnati born and bred webdev nerd who loves to build with Drupal, WordPress and Meteor.js."
baseurl: ""
url: "http://joecastelli.com"

# Build settings
markdown: kramdown
permalink: ':title'
sass:
  sass_dir: _sass
paginate: 5
highlighter: pygments